#!/bin/sh
# ImageMagick
test -f panda3d.png || convert ../models/plugin_images/installer.bmp -crop 163x180+0+3 panda3d.png
# I have to often restart because doxygen crashes.  What utter garbage.
test -z "$1" && rm -rf html latex
doxygen
# remove C++ source files; only retain headers
sed -i '/8cxx/d;/href="dir_/d' html/files.html latex/files.tex
# all headers are not in subdirs, so remove dirs as well
rm -f html/dir_* html/*8cxx* latex/*8cxx* latex/dir_*
# now, any item not defined in a header gets removed.
# none of the exported headers are removed in this way
# this *will* leave blanks in some inheritance graphs.
cd html
for x in class*.html; do
  case "$x" in
    *-members.html|classes.html) continue
  esac
  grep '#include &lt;' "$x" >/dev/null || echo $x
done | sed 's/class//;s/\.html//' | while read c; do
  echo "filter $c"
  p=class$c
  rm -f "$p.html" "$p-members.html" "class${c}__"[ig]*
  sed -i -e "/href=\"$p.html/d" annotated.html hierarchy.html
  sed -i -e "s%<dd>[^/]*href=\"$p.html[^/]*/a></dd>%%g" classes.html
  sed -E -i -e "s%<a[^>]*href=\"$p.html[^/]*/a>(, )?%%g;s%, </li>%</li>%;/160;<\\/li/d" functions_*.html functions.html
  sed -i -e "/href=\"\\\$$p.html/d" $(fgrep -l "href=\"\$$p.html" inherit_graph*.map *__inherit__graph.map)
  sed -i -e "/xlink:href=\"$p.html/{:a N; /<\/g>/!ba; d;}" $(fgrep -l "xlink:href=\"$p.html" inherit_graph*.svg *__inherit__graph.svg)
  sed -i -E -e "/[iI]mplemented/{s%<a[^/]*href=\"$p.html[^/]*/a>(, )?%%;s/, (and )?\\.</.</;/.* in \\.<.*/d;}" $(fgrep -l $p.html class*.html) 2>/dev/null
done
